"""add_user_settings_table_fixed

Revision ID: 08230f29a0db
Revises: 59b5bd032377
Create Date: 2025-06-16 11:14:07.407694

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "08230f29a0db"
down_revision: Union[str, None] = "d9115a6b0bc5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_settings",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("theme", sa.String(length=20), nullable=False),
        sa.Column("preferred_currency", sa.String(length=3), nullable=False),
        sa.Column("date_format", sa.String(length=20), nullable=False),
        sa.Column("timezone", sa.String(length=50), nullable=False),
        sa.Column("preferred_data_provider", sa.String(length=50), nullable=False),
        sa.Column("price_update_frequency", sa.Integer(), nullable=False),
        sa.Column("enable_real_time_updates", sa.Boolean(), nullable=False),
        sa.Column("default_dashboard_view", sa.String(length=50), nullable=False),
        sa.Column("items_per_page", sa.Integer(), nullable=False),
        sa.Column("show_advanced_metrics", sa.Boolean(), nullable=False),
        sa.Column("email_notifications_enabled", sa.Boolean(), nullable=False),
        sa.Column("notification_email", sa.String(length=255), nullable=True),
        sa.Column("price_alerts_enabled", sa.Boolean(), nullable=False),
        sa.Column("performance_alerts_enabled", sa.Boolean(), nullable=False),
        sa.Column("news_alerts_enabled", sa.Boolean(), nullable=False),
        sa.Column("daily_summary_enabled", sa.Boolean(), nullable=False),
        sa.Column("price_change_threshold", sa.Float(), nullable=True),
        sa.Column("portfolio_change_threshold", sa.Float(), nullable=True),
        sa.Column("share_portfolio_data", sa.Boolean(), nullable=False),
        sa.Column("enable_analytics_tracking", sa.Boolean(), nullable=False),
        sa.Column("chart_theme", sa.String(length=20), nullable=False),
        sa.Column("default_chart_period", sa.String(length=10), nullable=False),
        sa.Column("show_percentage_changes", sa.Boolean(), nullable=False),
        sa.Column("show_market_hours_only", sa.Boolean(), nullable=False),
        sa.Column("custom_dashboard_layout", sa.Text(), nullable=True),
        sa.Column("watchlist_settings", sa.Text(), nullable=True),
        sa.Column("alert_preferences", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_settings_id"), "user_settings", ["id"], unique=False)
    op.create_index(
        op.f("ix_user_settings_user_id"), "user_settings", ["user_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_settings_user_id"), table_name="user_settings")
    op.drop_index(op.f("ix_user_settings_id"), table_name="user_settings")
    op.drop_table("user_settings")
    # ### end Alembic commands ###
