"""add_default_user_for_dev

Revision ID: fd5642662c22
Revises: cd99d6a21c5f
Create Date: 2025-06-17 07:41:53.540771

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fd5642662c22"
down_revision: Union[str, None] = "cd99d6a21c5f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create default user for development only
    import hashlib
    import os

    # Check if this is development environment
    if os.getenv("ENVIRONMENT", "production") != "production":
        # Simple password hashing (matching create_default_user.py approach)
        password = "password123"
        hashed_password = hashlib.sha256(password.encode()).hexdigest()

        op.execute(
            f"""
            INSERT INTO users (email, username, full_name, hashed_password, is_active, is_verified, is_superuser, preferred_currency, timezone, created_at, updated_at)
            VALUES (
                'user@example.com',
                'testuser',
                'Test User',
                '{hashed_password}',
                true,
                true,
                false,
                'USD',
                'UTC',
                NOW(),
                NOW()
            )
            ON CONFLICT (email) DO NOTHING;
            """
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
