"""Initial migration: create all tables

Revision ID: d9115a6b0bc5
Revises: 
Create Date: 2025-06-12 23:23:33.883583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d9115a6b0bc5"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assets",
        sa.Column("ticker", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column(
            "asset_type",
            sa.Enum(
                "STOCK",
                "BOND",
                "ETF",
                "MUTUAL_FUND",
                "CRYPTO",
                "CASH",
                "COMMODITY",
                "REAL_ESTATE",
                "OTHER",
                name="assettype",
            ),
            nullable=False,
        ),
        sa.Column(
            "category",
            sa.Enum(
                "EQUITY",
                "FIXED_INCOME",
                "ALTERNATIVE",
                "CASH_EQUIVALENT",
                "COMMODITY",
                "REAL_ESTATE",
                name="assetcategory",
            ),
            nullable=False,
        ),
        sa.Column("sector", sa.String(length=100), nullable=True),
        sa.Column("industry", sa.String(length=100), nullable=True),
        sa.Column("exchange", sa.String(length=20), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("country", sa.String(length=2), nullable=True),
        sa.Column("current_price", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("previous_close", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("day_change", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column(
            "day_change_percent", sa.Numeric(precision=8, scale=4), nullable=True
        ),
        sa.Column("market_cap", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("pe_ratio", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("dividend_yield", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("data_source", sa.String(length=50), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_assets_id"), "assets", ["id"], unique=False)
    op.create_index(op.f("ix_assets_ticker"), "assets", ["ticker"], unique=True)
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=True),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("preferred_currency", sa.String(length=3), nullable=False),
        sa.Column("timezone", sa.String(length=50), nullable=False),
        sa.Column("last_login", sa.DateTime(), nullable=True),
        sa.Column("email_verified_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "portfolio_snapshots",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("snapshot_date", sa.Date(), nullable=False),
        sa.Column("total_value", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column(
            "total_cost_basis", sa.Numeric(precision=20, scale=4), nullable=False
        ),
        sa.Column("cash_balance", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("invested_amount", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("total_gain_loss", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column(
            "total_gain_loss_percent", sa.Numeric(precision=8, scale=4), nullable=False
        ),
        sa.Column("daily_change", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column(
            "daily_change_percent", sa.Numeric(precision=8, scale=4), nullable=True
        ),
        sa.Column("equity_value", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column(
            "fixed_income_value", sa.Numeric(precision=20, scale=4), nullable=False
        ),
        sa.Column(
            "alternative_value", sa.Numeric(precision=20, scale=4), nullable=False
        ),
        sa.Column(
            "cash_equivalent_value", sa.Numeric(precision=20, scale=4), nullable=False
        ),
        sa.Column("commodity_value", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column(
            "real_estate_value", sa.Numeric(precision=20, scale=4), nullable=False
        ),
        sa.Column("number_of_positions", sa.Integer(), nullable=False),
        sa.Column("number_of_assets", sa.Integer(), nullable=False),
        sa.Column("portfolio_beta", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("sharpe_ratio", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("volatility", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("benchmark_return", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("alpha", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("calculation_method", sa.String(length=50), nullable=False),
        sa.Column(
            "data_quality_score", sa.Numeric(precision=3, scale=2), nullable=True
        ),
        sa.Column("notes", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "snapshot_date", name="unique_user_snapshot_date"
        ),
    )
    op.create_index(
        op.f("ix_portfolio_snapshots_id"), "portfolio_snapshots", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_portfolio_snapshots_snapshot_date"),
        "portfolio_snapshots",
        ["snapshot_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_portfolio_snapshots_user_id"),
        "portfolio_snapshots",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "positions",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("asset_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column(
            "average_cost_per_share", sa.Numeric(precision=12, scale=4), nullable=False
        ),
        sa.Column(
            "total_cost_basis", sa.Numeric(precision=20, scale=4), nullable=False
        ),
        sa.Column("account_name", sa.String(length=100), nullable=True),
        sa.Column("notes", sa.String(length=500), nullable=True),
        sa.Column("tax_lot_method", sa.String(length=20), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_positions_asset_id"), "positions", ["asset_id"], unique=False
    )
    op.create_index(op.f("ix_positions_id"), "positions", ["id"], unique=False)
    op.create_index(
        op.f("ix_positions_user_id"), "positions", ["user_id"], unique=False
    )
    op.create_table(
        "price_history",
        sa.Column("asset_id", sa.Integer(), nullable=False),
        sa.Column("price_date", sa.Date(), nullable=False),
        sa.Column("open_price", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("high_price", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("low_price", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("close_price", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("adjusted_close", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("volume", sa.Integer(), nullable=True),
        sa.Column("daily_return", sa.Numeric(precision=8, scale=6), nullable=True),
        sa.Column("data_source", sa.String(length=50), nullable=True),
        sa.Column("is_adjusted", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("asset_id", "price_date", name="unique_asset_date"),
    )
    op.create_index(
        op.f("ix_price_history_asset_id"), "price_history", ["asset_id"], unique=False
    )
    op.create_index(op.f("ix_price_history_id"), "price_history", ["id"], unique=False)
    op.create_index(
        op.f("ix_price_history_price_date"),
        "price_history",
        ["price_date"],
        unique=False,
    )
    op.create_table(
        "transactions",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("asset_id", sa.Integer(), nullable=False),
        sa.Column("position_id", sa.Integer(), nullable=True),
        sa.Column(
            "transaction_type",
            sa.Enum(
                "BUY",
                "SELL",
                "DIVIDEND",
                "SPLIT",
                "MERGER",
                "SPINOFF",
                "TRANSFER_IN",
                "TRANSFER_OUT",
                "CASH_DEPOSIT",
                "CASH_WITHDRAWAL",
                "FEE",
                "INTEREST",
                "OTHER",
                name="transactiontype",
            ),
            nullable=False,
        ),
        sa.Column("transaction_date", sa.Date(), nullable=False),
        sa.Column("settlement_date", sa.Date(), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("price_per_share", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("commission", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("regulatory_fees", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("other_fees", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("tax_withheld", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("account_name", sa.String(length=100), nullable=True),
        sa.Column("order_id", sa.String(length=100), nullable=True),
        sa.Column("confirmation_number", sa.String(length=100), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("data_source", sa.String(length=50), nullable=True),
        sa.Column("external_id", sa.String(length=100), nullable=True),
        sa.Column("split_ratio", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("exchange_rate", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["position_id"],
            ["positions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_transactions_asset_id"), "transactions", ["asset_id"], unique=False
    )
    op.create_index(op.f("ix_transactions_id"), "transactions", ["id"], unique=False)
    op.create_index(
        op.f("ix_transactions_position_id"),
        "transactions",
        ["position_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transactions_transaction_date"),
        "transactions",
        ["transaction_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transactions_transaction_type"),
        "transactions",
        ["transaction_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transactions_user_id"), "transactions", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transactions_user_id"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_transaction_type"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_transaction_date"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_position_id"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_id"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_asset_id"), table_name="transactions")
    op.drop_table("transactions")
    op.drop_index(op.f("ix_price_history_price_date"), table_name="price_history")
    op.drop_index(op.f("ix_price_history_id"), table_name="price_history")
    op.drop_index(op.f("ix_price_history_asset_id"), table_name="price_history")
    op.drop_table("price_history")
    op.drop_index(op.f("ix_positions_user_id"), table_name="positions")
    op.drop_index(op.f("ix_positions_id"), table_name="positions")
    op.drop_index(op.f("ix_positions_asset_id"), table_name="positions")
    op.drop_table("positions")
    op.drop_index(
        op.f("ix_portfolio_snapshots_user_id"), table_name="portfolio_snapshots"
    )
    op.drop_index(
        op.f("ix_portfolio_snapshots_snapshot_date"), table_name="portfolio_snapshots"
    )
    op.drop_index(op.f("ix_portfolio_snapshots_id"), table_name="portfolio_snapshots")
    op.drop_table("portfolio_snapshots")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_assets_ticker"), table_name="assets")
    op.drop_index(op.f("ix_assets_id"), table_name="assets")
    op.drop_table("assets")
    # ### end Alembic commands ###
